/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bet {
  'id' : bigint,
  'multiplier' : bigint,
  'stakeAmount' : bigint,
  'user' : Principal,
  'betType' : string,
  'betValue' : string,
  'periodId' : bigint,
  'outcome' : string,
  'payout' : bigint,
}
export interface Period {
  'id' : bigint,
  'startTime' : bigint,
  'status' : string,
  'result' : bigint,
}
export interface UserProfile {
  'principal' : Principal,
  'referralCode' : string,
  'username' : string,
  'balance' : bigint,
  'lastDailyBonus' : bigint,
  'totalBets' : bigint,
  'totalWins' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimDailyBonus' : ActorMethod<[], undefined>,
  'finalizePeriod' : ActorMethod<[], undefined>,
  'getBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentPeriod' : ActorMethod<[], [bigint, string]>,
  'getGameHistory' : ActorMethod<[], Array<Period>>,
  'getMyBets' : ActorMethod<[], Array<Bet>>,
  'getProfile' : ActorMethod<[], UserProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeBet' : ActorMethod<[string, string, bigint, bigint], undefined>,
  'register' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];