/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'referralCode' : IDL.Text,
  'username' : IDL.Text,
  'balance' : IDL.Nat,
  'lastDailyBonus' : IDL.Int,
  'totalBets' : IDL.Nat,
  'totalWins' : IDL.Nat,
});
export const Period = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'status' : IDL.Text,
  'result' : IDL.Nat,
});
export const Bet = IDL.Record({
  'id' : IDL.Nat,
  'multiplier' : IDL.Nat,
  'stakeAmount' : IDL.Nat,
  'user' : IDL.Principal,
  'betType' : IDL.Text,
  'betValue' : IDL.Text,
  'periodId' : IDL.Nat,
  'outcome' : IDL.Text,
  'payout' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimDailyBonus' : IDL.Func([], [], []),
  'finalizePeriod' : IDL.Func([], [], []),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentPeriod' : IDL.Func([], [IDL.Nat, IDL.Text], ['query']),
  'getGameHistory' : IDL.Func([], [IDL.Vec(Period)], ['query']),
  'getMyBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
  'getProfile' : IDL.Func([], [UserProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeBet' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'register' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'referralCode' : IDL.Text,
    'username' : IDL.Text,
    'balance' : IDL.Nat,
    'lastDailyBonus' : IDL.Int,
    'totalBets' : IDL.Nat,
    'totalWins' : IDL.Nat,
  });
  const Period = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'status' : IDL.Text,
    'result' : IDL.Nat,
  });
  const Bet = IDL.Record({
    'id' : IDL.Nat,
    'multiplier' : IDL.Nat,
    'stakeAmount' : IDL.Nat,
    'user' : IDL.Principal,
    'betType' : IDL.Text,
    'betValue' : IDL.Text,
    'periodId' : IDL.Nat,
    'outcome' : IDL.Text,
    'payout' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimDailyBonus' : IDL.Func([], [], []),
    'finalizePeriod' : IDL.Func([], [], []),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentPeriod' : IDL.Func([], [IDL.Nat, IDL.Text], ['query']),
    'getGameHistory' : IDL.Func([], [IDL.Vec(Period)], ['query']),
    'getMyBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
    'getProfile' : IDL.Func([], [UserProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeBet' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'register' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };